-- part2_SELECT_PRACTICE.sql
-- SELECT와 WHERE문 연습
-- 1. SALARY 값이 4000 이상, 8000 이하인 사원의
-- EMPLOYEE_ID와 FIRST_NAME 출력하기
SELECT EMPLOYEE_ID, FIRST_NAME
--, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 4000 AND 8000
--ORDER BY SALARY DESC
;


-- 2. SALARY 값이 10000 초과이거나
-- JOB_ID가 'ST_MAN'인 사원의
-- SALARY를 10배로 만든 TEN_SALARY열과
-- JOB_ID 출력
SELECT SALARY * 10 AS "TEN_SALARY", JOB_ID
FROM EMPLOYEES
WHERE 
	SALARY > 10000 OR 
	JOB_ID = 'ST_MAN'
--ORDER BY SALARY
;

-- 3. DEPARTMENT_ID가 10, 20, 30 중 하나이고
-- FIRST_NAME이 A로 시작하는 사원의 FIRST_NAME 출력
SELECT FIRST_NAME
, DEPARTMENT_ID
FROM EMPLOYEES
WHERE 
	DEPARTMENT_ID IN (10, 20, 30) AND 
	FIRST_NAME LIKE 'A%'
;

SELECT *
FROM EMPLOYEES;