-- part4_GROUP_BY_PRACTICE.sql
-- DEPARTMENT_ID별로 그룹화 하고
-- 그룹들에 대해서 최대 급여와 최소 급여의 차이를 구한 뒤
-- 그 차이가 5000 이상인 DEPARTMENT_ID와
-- 차이를 출력해보자.
SELECT DEPARTMENT_ID, 
MAX(SALARY) - MIN(SALARY) DIFF_SAL,
MAX(SALARY) MAX_SAL, MIN(SALARY) MIN_SAL
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID 
HAVING MAX(SALARY) - MIN(SALARY) >= 5000;